services:
  macos:
    image: dockurr/macos
    container_name: macos
    restart: always # Thêm dòng này
    environment:
      VERSION: "14"
      USERNAME: "Dev"
      PASSWORD: "@1U2I3o4p"
      RAM_SIZE: "48G"
      CPU_CORES: "16"
      DISK_SIZE: "512G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
